# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest
 
steps:
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.name "Dejan Petrov"
      git config --global user.email "dejan.petrov@dapmn.com"
- task: gitsync@1
  inputs:
    GitRepoUrl: 'https://dejan:$(MYPAT)@gitlab.dapmn.com/dejan/filemin-docker.git'