name : Docker-CI
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'filemin-docker:$(Build.BuildId)'  

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      displayName: 'Build the Docker image'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'filemin-docker'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'