version: '3.5'
services: 
    smb-webmin:
        build:
            context: . 
        container_name: ${CONTAINER_NAME_SAMBA}
        restart: unless-stopped
        image: filemin:latest
        ports:
            - ${SAMBA_WEBUI_PORT}:10000
        volumes: 
            - ${ROOT_SHARE_FOLDER}:/srv