version: '3.5'
services: 
    filemin:
        build:
            context: . 
        container_name: ${CONTAINER_NAME_FILEMIN}
        restart: unless-stopped
        image: filemin:latest
        ports:
            - ${FILEMIN_WEBUI_PORT}:10000
        volumes: 
            - ${ROOT_SHARE_FOLDER}:/mnt