name : Docker-CI
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'filemin-docker'

steps:
- task: Docker@2
  displayName: Login
  inputs:
    containerRegistry: 'Docker Hub'
    command: 'login'
- task: CmdLine@2
  displayName: Build
  inputs:
    script: |
      docker run --privileged --rm tonistiigi/binfmt --install arm64
      docker run --privileged --rm tonistiigi/binfmt
      docker buildx create --use
      docker buildx build --platform linux/amd64,linux/arm64 \
        -t $(ImageName):$(build.buildNumber) \
        -t $(ImageName):latest \
        --push \
        .