trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: curl -u $(username):$(password) https://jenkins.dapmn.com/job/filemin-docker/build?token=$(token)
  displayName: 'Triggering Jenkins build for filemin-docker'

