# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name : Sync
trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.name "Dejan Petrov"
      git config --global user.email "dejan.petrov@dapmn.com"
- task: gitsync@1
  inputs:
    GitRepoUrl: 'https://dejan:$(MYPATGITLAB)@gitlab.dapmn.com/dejan/filemin-docker.git'
- task: gitsync@1
  inputs:
    GitRepoUrl: 'https://$(MYPAT)@github.com/dejan995/filemin-docker.git'